name: acr test

permissions:
  contents: read
  issues: write

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out
      #   uses: action/checkout@v4
        
      - name: Acr bot
        uses: AutoCodeRoverSG/code-rover-bot@v0.0.2
        env:
          TARGET_REPO_PATH: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
